name: Apply SharePoint Metadata Schema

on:
  push:
    paths:
      - 'workflows/contracts/metadata-schema.json'
  workflow_dispatch:

jobs:
  apply-metadata:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests msal
        
    - name: Apply metadata schema to SharePoint
      env:
        SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
        SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
      run: |
        python workflows/contracts/apply_metadata.py